// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCConfigurator.DataAccess.Mssql.EntityFramework;

namespace PCConfigurator.DataAccess.Mssql.EntityFramework.Migrations
{
    [DbContext(typeof(PCConfiguratorDBContext))]
    partial class PCConfiguratorDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCConfigurator.Core.ComponentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("component_types");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "GPU"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "RAM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
